E2Helper.Descriptions["gprpIsWanted(e:)"] = "Returns player wanted"
E2Helper.Descriptions["gprpUnWanted(e:)"] = "Unwanted player if you CP"
E2Helper.Descriptions["gprpGetWantedReason(e:)"] = "Returns player wanted reason"
E2Helper.Descriptions["gprpWanted(e:string reason)"] = "Wanted player if you CP"
E2Helper.Descriptions["gprpLottery()"] = "Start lottery if you mayor"