E2Helper.Descriptions["shipmentName"] = "Returns the name of the shipment."
E2Helper.Descriptions["shipmentType"] = "Returns the class of the weapon the shipment spawns."
E2Helper.Descriptions["shipmentPrice"] = "Returns the price of the shipment."
E2Helper.Descriptions["shipmentAmount"] = "Returns the number of guns in the shipment."
E2Helper.Descriptions["shipmentModel"] = "Returns the model of the gun in the shipment."
E2Helper.Descriptions["isShipment"] = "Returns whether the entity is a shipment or not."
